export const siteConfig = {
  name: "Ruizhe (Jason) Dai - Data Science & ML Engineer",
  authorName: "Ruizhe (Jason) Dai",
  username: "JasonDai1219",
  description:
    "Ruizhe (Jason) Dai is a Data Science and Machine Learning engineer focused on building data-driven systems and AI-assisted tools. Experience includes disease progression modeling, multimodal model evaluation, and large-scale data pipelines across research and industry.",
  url: "https://jason-website-ten.vercel.app",
  links: {
    github: "https://github.com/JasonDai1219",
    linkedin: "https://www.linkedin.com/in/jason-dai9",
    email: "mailto:dai9@seas.upenn.edu",
    repo: "https://github.com/JasonDai1219/Jason-website",
  },
  ogImage: "/og.png",
  iconIco: "/favicon.ico",
  logoIcon: "/logo.png",
  keywords: [
    "Ruizhe Dai",
    "Jason Dai",
    "Data Science",
    "Machine Learning",
    "ML Engineering",
    "AI Systems",
    "Python",
    "SQL",
    "PyTorch",
    "Scikit-Learn",
    "Spark",
    "Airflow",
    "AWS",
    "PostgreSQL",
    "University of Pennsylvania",
    "UC San Diego",
  ],
};